local theme = require("colors/theme")

theme.highlight_fg('CmpItemAbbr', theme.colors.white)
theme.highlight_fg('CmpBorder', theme.colors.grey)
theme.highlight_fg('CmpDocBorder', theme.colors.grey)
theme.highlight_fg('CmpItemKindConstant', theme.base16.base09)
theme.highlight_fg('CmpItemKindFunction', theme.base16.base0D)
theme.highlight_fg('CmpItemKindIdentifier', theme.base16.base08)
theme.highlight_fg('CmpItemKindField', theme.base16.base08)
theme.highlight_fg('CmpItemKindVariable', theme.base16.base0C)
theme.highlight_fg('CmpItemKindSnippet', theme.colors.red)
theme.highlight_fg('CmpItemKindText', theme.base16.base0B)
theme.highlight_fg('CmpItemKindStructure', theme.base16.base0C)
theme.highlight_fg('CmpItemKindType', theme.base16.base0A)
theme.highlight_fg('CmpItemKindKeyword', theme.base16.base07)
theme.highlight_fg('CmpItemKindMethod', theme.base16.base0D)
theme.highlight_fg('CmpItemKindConstructor', theme.colors.blue)
theme.highlight_fg('CmpItemKindFolder', theme.base16.base07)
theme.highlight_fg('CmpItemKindModule', theme.base16.base0A)
theme.highlight_fg('CmpItemKindProperty', theme.base16.base08)
theme.highlight_fg('CmpItemKindUnit', theme.base16.base0C)
theme.highlight_fg('CmpItemKindFile', theme.base16.base07)
theme.highlight_fg('CmpItemKindColor', theme.colors.red)
theme.highlight_fg('CmpItemKindReference', theme.base16.base05)
theme.highlight_fg('CmpItemKindStruct', theme.base16.base0C)
theme.highlight_fg('CmpItemKindOperator', theme.base16.base05)
theme.highlight_fg('CmpItemKindTypeParameter', theme.base16.base08)
theme.highlight_gui('highlightCmpItemAbbrMatch', 'bold')
theme.highlight_fg('highlightCmpItemAbbrMatch', theme.colors.blue)
theme.highlight_fg_bg('CmpItemMenu', theme.colors.white, theme.colors.blue)
theme.highlight_bg('Pmenu', theme.colors.one_bg)
theme.highlight_bg('PmenuSbar', theme.colors.darker_black)
theme.highlight_fg_bg('PmenuSel', theme.colors.black, theme.colors.nord_blue)
theme.highlight_bg('PmenuThumb', theme.colors.nord_blue)
theme.highlight_fg("CmpItemAbbrMatch", theme.colors.white)
theme.highlight_fg("CmpItemKind", theme.colors.white)
