local t = require("colors/theme")
local fg_bg = t.highlight_fg_bg

fg_bg("DevIconc", t.blue, "NONE")
fg_bg("DevIconcss", t.blue, "NONE")
fg_bg("DevIcondeb", t.teal, "NONE")
fg_bg("DevIconDockerfile", t.teal, "NONE")
fg_bg("DevIconhtml", t.red, "NONE")
fg_bg("DevIconjpeg", t.violet, "NONE")
fg_bg("DevIconjpg", t.violet, "NONE")
fg_bg("DevIconjs", t.yellow, "NONE")
fg_bg("DevIconjson", t.yellow, "NONE")
fg_bg("DevIconkt", t.orange, "NONE")
fg_bg("DevIconlock", t.red, "NONE")
fg_bg("DevIconlua", t.blue, "NONE")
fg_bg("DevIconmp3", t.fg, "NONE")
fg_bg("DevIconmp4", t.fg, "NONE")
fg_bg("DevIconout", t.fg, "NONE")
fg_bg("DevIconpng", t.violet, "NONE")
fg_bg("DevIconpy", t.teal, "NONE")
fg_bg("DevIcontoml", t.blue, "NONE")
fg_bg("DevIconts", t.teal, "NONE")
fg_bg("DevIconttf", t.fg, "NONE")
fg_bg("DevIconrb", t.red, "NONE")
fg_bg("DevIconrpm", t.orange, "NONE")
fg_bg("DevIconvue", t.green, "NONE")
fg_bg("DevIconwoff", t.fg, "NONE")
fg_bg("DevIconwoff2", t.fg, "NONE")
fg_bg("DevIconxz", t.yellow, "NONE")
fg_bg("DevIconzip", t.yellow, "NONE")
fg_bg("DevIcongo", t.teal, "NONE")
