local t = require("colors/theme")
local fg_bg = t.highlight_fg_bg
local fg = t.highlight_fg
local bg = t.highlight_bg

fg_bg("RenderMarkdownH1Bg", t.blue, t.bg)
fg_bg("RenderMarkdownH2Bg", t.blue, t.bg)
fg_bg("RenderMarkdownH3Bg", t.blue, t.bg)
fg_bg("RenderMarkdownH4Bg", t.blue, t.bg)
fg_bg("RenderMarkdownH5Bg", t.blue, t.bg)
fg_bg("RenderMarkdownH6Bg", t.blue, t.bg)
bg("RenderMarkdownCode", t.bg1)
fg_bg("RenderMarkdownCodeInline", t.bg, t.blue)
fg("RenderMarkdownInlineHighlight", t.blue)
fg("RenderMarkdownBullet", t.blue)
fg_bg("RenderMarkdownQuote", t.blue, t.bg)
fg("RenderMarkdownDash", t.fgSubtle)
fg("RenderMarkdownSign", t.blue)
fg("RenderMarkdownMath", t.blue)
fg("RenderMarkdownHtmlComment", t.blue)
fg("RenderMarkdownLink", t.blue)
fg("RenderMarkdownWikiLink", t.blue)
fg("RenderMarkdownUnchecked", t.blue)
fg("RenderMarkdownChecked", t.blue)
fg("RenderMarkdownTodo", t.blue)
fg("RenderMarkdownTableHead", t.blue)
fg("RenderMarkdownTableRow", t.blue)
fg("RenderMarkdownTableFill", t.blue)
fg("RenderMarkdownSuccess", t.violet)
fg("RenderMarkdownInfo", t.blue)
fg("RenderMarkdownHint", t.green)
fg("RenderMarkdownWarn", t.yellow)
fg("RenderMarkdownError", t.red)
