local theme = require("colors/theme")
theme.highlight_fg('Boolean', theme.base16.base09)
theme.highlight_fg('Character', theme.base16.base08)
theme.highlight_fg('Conditional', theme.base16.base0C)
theme.highlight_fg('Constant', theme.base16.base08)
theme.highlight_fg('Comment', theme.base16.base02)
theme.highlight_fg('Define', theme.base16.base0C)
theme.highlight_fg('Delimiter', theme.base16.base07)
theme.highlight_fg('Float', theme.base16.base09)
theme.highlight_fg('Function', theme.base16.base0C)
theme.highlight_fg('Identifier', theme.base16.base08)
theme.highlight_fg('Include', theme.base16.base0C)
theme.highlight_fg('Keyword', theme.base16.base0C)
theme.highlight_fg('Label', theme.base16.base08)
theme.highlight_fg('Number', theme.base16.base09)
theme.highlight_fg('Operator', theme.base16.base05)
theme.highlight_fg('PreProc', theme.base16.base08)
theme.highlight_fg('Repeat', theme.base16.base08)
theme.highlight_fg('Special', theme.base16.base0C)
theme.highlight_fg('SpecialChar', theme.base16.base07)
theme.highlight_fg('Statement', theme.base16.base08)
theme.highlight_fg('StorageClass', theme.base16.base08)
theme.highlight_fg('String', theme.base16.base0B)
theme.highlight_fg('Structure', theme.base16.base0C)
theme.highlight_fg('Tag', theme.base16.base08)
theme.highlight_fg_bg('Todo', theme.base16.base00, theme.base16.base0D)
theme.highlight_fg('Type', theme.base16.base08)
theme.highlight_fg('Typedef', theme.base16.base08)
