require("colors/highlights/syntax")
require("colors/highlights/cmp")
require("colors/highlights/indent-blank-line")
require("colors/highlights/misc")
require("colors/highlights/devicons")
require("colors/highlights/nvimtree")
require("colors/highlights/telescope")
